# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b0b0ef4fea194f25647c75b16387607fdef46c6c3c98a43aa16d8af3cfc5f15c8ef8304a9a58b9ab1ed84f3d84f4a5f882685e8df8a72aae9d74f8c5d7b2a0

test:
  secret_key_base: dcda718cb64fb2f797062e62716c19743ec3a5706d81d59d5f1f813441d69026d9921d203f44a0b0d40a9ea37325c038eb3eb432fe9e6bd107d93417f0760e12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
